export const competitionsData = [
  {
    id: 1,
    title: 'National AI Hackathon 2026',
    category: 'Artificial Intelligence',
    organizer: 'Ministry of Communications',
    level: 'Advanced',
    teamSize: '2-4 members',
    registrationDeadline: '2026-07-25',
    startDate: '2026-08-01',
    endDate: '2026-08-03',
    prize: '$10,000',
    participants: 342,
    description: 'A 48-hour hackathon challenging teams to build AI-powered solutions for real-world problems in healthcare, education, and sustainability.',
    requirements: ['Team of 2-4 students', 'Basic ML/AI knowledge', 'Laptop with development environment'],
    timeline: [
      { label: 'Registration Opens', date: '2026-06-01' },
      { label: 'Registration Closes', date: '2026-07-25' },
      { label: 'Hackathon Kickoff', date: '2026-08-01' },
      { label: 'Final Submission', date: '2026-08-03' },
      { label: 'Winners Announced', date: '2026-08-10' },
    ],
    rules: [
      'All code must be written during the competition window.',
      'Teams may use open-source libraries and pretrained models.',
      'Final submission must include a working demo and a 3-minute pitch video.',
    ],
  },
  {
    id: 2,
    title: 'Compass UI/UX Design Challenge',
    category: 'Design',
    organizer: 'Compass Academy',
    level: 'Intermediate',
    teamSize: 'Individual',
    registrationDeadline: '2026-07-22',
    startDate: '2026-07-28',
    endDate: '2026-08-04',
    prize: '$2,000',
    participants: 156,
    description: 'Redesign a real product experience end-to-end: research, wireframes, and a polished high-fidelity prototype in Figma.',
    requirements: ['Figma account', 'Basic design portfolio', 'Individual participation only'],
    timeline: [
      { label: 'Registration Opens', date: '2026-06-15' },
      { label: 'Registration Closes', date: '2026-07-22' },
      { label: 'Brief Released', date: '2026-07-28' },
      { label: 'Submission Deadline', date: '2026-08-04' },
      { label: 'Results Published', date: '2026-08-11' },
    ],
    rules: [
      'Submissions must be original work created during the challenge window.',
      'Prototype must be shared as a public Figma link.',
      'Judging criteria: usability, visual design, and presentation.',
    ],
  },
  {
    id: 3,
    title: 'Web Development Sprint',
    category: 'Software Engineering',
    organizer: 'Al-Azhar University Engineering Club',
    level: 'Beginner',
    teamSize: '1-3 members',
    registrationDeadline: '2026-07-15',
    startDate: '2026-07-16',
    endDate: '2026-07-19',
    prize: '$1,000',
    participants: 210,
    description: 'A campus-wide sprint to build a fully functional web app from scratch in under 72 hours, judged live by industry mentors.',
    requirements: ['Basic HTML/CSS/JS', 'GitHub account', 'Team of up to 3'],
    timeline: [
      { label: 'Registration Opens', date: '2026-06-20' },
      { label: 'Registration Closes', date: '2026-07-15' },
      { label: 'Sprint Starts', date: '2026-07-16' },
      { label: 'Sprint Ends', date: '2026-07-19' },
      { label: 'Live Judging', date: '2026-07-20' },
    ],
    rules: [
      'Repository must be public and created after the sprint start date.',
      'Each team presents a 5-minute live demo to judges.',
      'Use of AI coding assistants is allowed but must be disclosed.',
    ],
  },
  {
    id: 4,
    title: 'Cybersecurity Capture The Flag',
    category: 'Cyber Security',
    organizer: 'Compass Academy',
    level: 'Advanced',
    teamSize: '1-4 members',
    registrationDeadline: '2026-06-30',
    startDate: '2026-07-05',
    endDate: '2026-07-06',
    prize: '$3,500',
    participants: 128,
    description: 'A CTF-style competition covering web exploitation, cryptography, reverse engineering, and network forensics challenges.',
    requirements: ['Basic networking & security knowledge', 'Personal laptop', 'CTF platform account'],
    timeline: [
      { label: 'Registration Opens', date: '2026-05-25' },
      { label: 'Registration Closes', date: '2026-06-30' },
      { label: 'CTF Opens', date: '2026-07-05' },
      { label: 'CTF Closes', date: '2026-07-06' },
      { label: 'Scoreboard Finalized', date: '2026-07-07' },
    ],
    rules: [
      'Flag sharing between teams is strictly prohibited.',
      'Automated scanning tools against the platform are not allowed.',
      'Top 10 teams will be invited to a live award ceremony.',
    ],
  },
  {
    id: 5,
    title: 'Mobile App Innovation Award',
    category: 'Mobile Development',
    organizer: 'Ministry of Communications',
    level: 'Intermediate',
    teamSize: '1-3 members',
    registrationDeadline: '2026-08-10',
    startDate: '2026-08-15',
    endDate: '2026-09-01',
    prize: '$5,000',
    participants: 89,
    description: 'Design and build a mobile app addressing a local community problem, judged on impact, usability, and technical execution.',
    requirements: ['Working prototype (Flutter, React Native, or native)', 'Demo video', 'Team of up to 3'],
    timeline: [
      { label: 'Registration Opens', date: '2026-07-10' },
      { label: 'Registration Closes', date: '2026-08-10' },
      { label: 'Development Window Starts', date: '2026-08-15' },
      { label: 'Final Submission', date: '2026-09-01' },
      { label: 'Winners Announced', date: '2026-09-10' },
    ],
    rules: [
      'App must run on at least one mobile platform (iOS or Android).',
      'Submissions must include source code and a 2-minute demo video.',
      'Judging weighs social impact heavily alongside technical quality.',
    ],
  },
  {
    id: 6,
    title: 'Data Science Case Competition',
    category: 'Data Science',
    organizer: 'Compass Academy',
    level: 'Intermediate',
    teamSize: '2-4 members',
    registrationDeadline: '2026-06-10',
    startDate: '2026-06-15',
    endDate: '2026-06-20',
    prize: '$2,500',
    participants: 175,
    description: 'Teams analyze a real anonymized dataset and present actionable business recommendations to a panel of industry judges.',
    requirements: ['Python or R proficiency', 'Data visualization skills', 'Team of 2-4'],
    timeline: [
      { label: 'Registration Opens', date: '2026-05-15' },
      { label: 'Registration Closes', date: '2026-06-10' },
      { label: 'Dataset Released', date: '2026-06-15' },
      { label: 'Final Report Due', date: '2026-06-20' },
      { label: 'Results Announced', date: '2026-06-27' },
    ],
    rules: [
      'Final deliverable is a report plus a 10-minute presentation.',
      'External datasets may be used only to supplement the provided one.',
      'All team members must present during judging.',
    ],
  },
];