import coverFlutter from './assets/course-flutter-workshop.jpg';
import coverBusiness from './assets/course-fullstack-development.jpg';
import coverUiux from './assets/course-uiux-design.jpg';
import coverAi from './assets/course-ai-machine-learning.jpg';
import coverSoftwareEng from './assets/course-software-engineering.jpg';

export const coursesData = [
  {
    id: 1,
    category: 'Software Engineering',
    title: 'Designing and building scalable and maintainable software systems.',
    instructor: 'Eng. Ahmad Khalil',
    instructorTitle: 'Senior Software Architect at Compass Academy',
    instructorBio: 'Ahmad has 10+ years building large-scale systems and leads the architecture track at Compass.',
    level: 'Intermediate',
    duration: '8 Weeks',
    lessons: 24,
    rating: 4.8,
    students: 1240,
    price: 149,
    coverImage: coverSoftwareEng,
    description: 'This course teaches you how to design robust software architectures used in real production systems. You will learn design patterns, system design principles, and how to build applications that scale.',
    whatYouWillLearn: [
      'Software architecture fundamentals',
      'Design patterns & best practices',
      'Scalability and performance optimization',
      'Clean code and maintainability',
    ],
    requirements: ['Basic programming knowledge', 'Understanding of OOP concepts'],
    modules: [
      {
        id: 'se-m1',
        title: 'Foundations of Software Architecture',
        lessons: [
          { id: 'se-l1', title: 'Introduction to Software Architecture', duration: '15 min',
            content: 'We explore what software architecture means, why it matters early on, and how architectural decisions affect a system\'s lifetime.',
            keyPoints: ['What is architecture vs design', 'Architectural qualities (ilities)', 'Common architectural styles'] },
          { id: 'se-l2', title: 'Layered vs Microservices Architecture', duration: '20 min',
            content: 'A comparison between monolithic layered systems and microservices, including trade-offs in complexity, deployment, and team structure.',
            keyPoints: ['Monolith vs microservices', 'Service boundaries', 'Deployment complexity'] },
        ],
      },
      {
        id: 'se-m2',
        title: 'Design Patterns in Practice',
        lessons: [
          { id: 'se-l3', title: 'Structural & Behavioral Patterns', duration: '18 min',
            content: 'Deep dive into patterns like Adapter, Decorator, Observer, and Strategy with real code examples.',
            keyPoints: ['Structural patterns', 'Behavioral patterns', 'When NOT to use a pattern'] },
          { id: 'se-l4', title: 'Applying Patterns to Real Projects', duration: '22 min',
            content: 'How to refactor an existing messy codebase by introducing design patterns incrementally.',
            keyPoints: ['Refactoring safely', 'Identifying code smells', 'Pattern combinations'] },
        ],
      },
      {
        id: 'se-m3',
        title: 'Scalability & Performance',
        lessons: [
          { id: 'se-l5', title: 'Caching & Load Balancing', duration: '16 min',
            content: 'Learn caching strategies (client, CDN, server-side) and load balancing algorithms used in production.',
            keyPoints: ['Cache invalidation', 'Load balancing strategies', 'CDN basics'] },
          { id: 'se-l6', title: 'Performance Profiling', duration: '19 min',
            content: 'Hands-on profiling of a slow API endpoint to identify and fix bottlenecks.',
            keyPoints: ['Profiling tools', 'Reading flame graphs', 'Common bottlenecks'] },
        ],
      },
    ],
    assignments: [
      { id: 'se-a1', title: 'Architecture Diagram Submission', dueInDays: 4,
        description: 'Submit a system architecture diagram for a given case study, justifying your design choices.' },
      { id: 'se-a2', title: 'Refactoring Exercise', dueInDays: 9,
        description: 'Refactor the provided legacy codebase by applying at least two design patterns.' },
    ],
    resources: [
      { id: 'se-r1', title: 'Clean Architecture Handbook', type: 'pdf', url: '#' },
      { id: 'se-r2', title: 'Design Patterns Cheat Sheet', type: 'link', url: '#' },
    ],
  },
  {
    id: 2,
    category: 'Flutter Masterclass',
    title: 'Build Production-Ready Apps',
    instructor: 'Eng. Sara Youssef',
    instructorTitle: 'Mobile Engineering Lead',
    instructorBio: 'Sara has shipped 15+ Flutter apps to production and mentors mobile developers at Compass.',
    level: 'Beginner',
    duration: '6 Weeks',
    lessons: 18,
    rating: 4.6,
    students: 980,
    price: 99,
    coverImage: coverFlutter,
    description: 'Learn Flutter from scratch and build cross-platform mobile apps ready for the App Store and Google Play.',
    whatYouWillLearn: [
      'Dart programming basics',
      'Flutter widgets & UI building',
      'State management',
      'Publishing apps to stores',
    ],
    requirements: ['No prior experience needed'],
    modules: [
      {
        id: 'fl-m1',
        title: 'Dart & Flutter Basics',
        lessons: [
          { id: 'fl-l1', title: 'Dart Syntax Essentials', duration: '14 min',
            content: 'Cover variables, functions, classes, and null safety in Dart before touching Flutter.',
            keyPoints: ['Null safety', 'Classes & constructors', 'Async/await basics'] },
          { id: 'fl-l2', title: 'Flutter Widget Tree', duration: '17 min',
            content: 'Understand how Flutter builds UI as a tree of widgets and how StatelessWidget differs from StatefulWidget.',
            keyPoints: ['Widget tree concept', 'Stateless vs Stateful', 'Hot reload workflow'] },
        ],
      },
      {
        id: 'fl-m2',
        title: 'Building UI',
        lessons: [
          { id: 'fl-l3', title: 'Layouts & Navigation', duration: '20 min',
            content: 'Build multi-screen apps using Rows, Columns, and Navigator for screen transitions.',
            keyPoints: ['Row/Column/Stack', 'Named routes', 'Passing data between screens'] },
          { id: 'fl-l4', title: 'State Management with Provider', duration: '23 min',
            content: 'Introduce the Provider package to manage shared state across widgets cleanly.',
            keyPoints: ['ChangeNotifier', 'Consumer widget', 'Avoiding prop drilling'] },
        ],
      },
      {
        id: 'fl-m3',
        title: 'Shipping to Stores',
        lessons: [
          { id: 'fl-l5', title: 'Testing & Debugging', duration: '15 min',
            content: 'Write widget tests and use Flutter DevTools to catch bugs before release.',
            keyPoints: ['Widget testing', 'DevTools basics', 'Common release bugs'] },
          { id: 'fl-l6', title: 'Publishing to App Store & Play Store', duration: '18 min',
            content: 'Step-by-step walkthrough of app signing, store listings, and submission requirements.',
            keyPoints: ['App signing', 'Store listing assets', 'Review guidelines'] },
        ],
      },
    ],
    assignments: [
      { id: 'fl-a1', title: 'Build a Todo App UI', dueInDays: 3,
        description: 'Create a Todo app UI with add/delete functionality using StatefulWidget.' },
      { id: 'fl-a2', title: 'Add State Management', dueInDays: 8,
        description: 'Refactor your Todo app to use Provider instead of local setState.' },
    ],
    resources: [
      { id: 'fl-r1', title: 'Flutter Widget Catalog', type: 'link', url: '#' },
      { id: 'fl-r2', title: 'Dart Style Guide', type: 'pdf', url: '#' },
    ],
  },
  {
    id: 3,
    category: 'AI Engineering',
    title: 'AI & Machine Learning Engineering: Practical Approach',
    instructor: 'Dr. Omar Fares',
    instructorTitle: 'Head of AI Research at Compass Institute',
    instructorBio: 'Dr. Fares has published in top ML conferences and leads applied AI projects across industries.',
    level: 'Advanced',
    duration: '10 Weeks',
    lessons: 32,
    rating: 4.9,
    students: 2100,
    price: 199,
    coverImage: coverAi,
    description: 'A hands-on course covering machine learning engineering practices used in real AI products, from data pipelines to model deployment.',
    whatYouWillLearn: [
      'Machine learning fundamentals',
      'Model training & evaluation',
      'Deployment pipelines (MLOps)',
      'Real-world AI case studies',
    ],
    requirements: ['Python programming', 'Basic statistics'],
    modules: [
      {
        id: 'ai-m1',
        title: 'Foundations of Machine Learning',
        lessons: [
          { id: 'ai-l1', title: 'Supervised vs Unsupervised Learning', duration: '16 min',
            content: 'Understand the difference between labeled and unlabeled learning problems with real examples.',
            keyPoints: ['Classification vs regression', 'Clustering basics', 'Choosing the right approach'] },
          { id: 'ai-l2', title: 'Feature Engineering Basics', duration: '19 min',
            content: 'Learn how to transform raw data into meaningful features that improve model performance.',
            keyPoints: ['Handling missing data', 'Encoding categorical features', 'Feature scaling'] },
        ],
      },
      {
        id: 'ai-m2',
        title: 'Model Training & Evaluation',
        lessons: [
          { id: 'ai-l3', title: 'Cross-Validation Techniques', duration: '18 min',
            content: 'Explore k-fold cross-validation and why it gives a more reliable estimate of model performance.',
            keyPoints: ['K-fold CV', 'Train/test/validation splits', 'Data leakage risks'] },
          { id: 'ai-l4', title: 'Metrics & Overfitting', duration: '21 min',
            content: 'Learn precision, recall, F1-score, and how to detect and fix overfitting.',
            keyPoints: ['Precision vs recall', 'Confusion matrix', 'Regularization techniques'] },
        ],
      },
      {
        id: 'ai-m3',
        title: 'Deployment (MLOps)',
        lessons: [
          { id: 'ai-l5', title: 'Building Data Pipelines', duration: '17 min',
            content: 'Design a repeatable pipeline that ingests, cleans, and prepares data for training.',
            keyPoints: ['ETL basics', 'Pipeline automation', 'Data versioning'] },
          { id: 'ai-l6', title: 'Model Serving & Monitoring', duration: '20 min',
            content: 'Deploy a trained model behind an API and monitor it for performance drift in production.',
            keyPoints: ['Model serving options', 'Latency vs throughput', 'Drift monitoring'] },
        ],
      },
    ],
    assignments: [
      { id: 'ai-a1', title: 'Train a Classification Model', dueInDays: 5,
        description: 'Train and evaluate a classification model on the provided dataset, reporting key metrics.' },
      { id: 'ai-a2', title: 'Deploy Model via API', dueInDays: 12,
        description: 'Wrap your trained model in a simple REST API and document the endpoints.' },
    ],
    resources: [
      { id: 'ai-r1', title: 'MLOps Handbook', type: 'pdf', url: '#' },
      { id: 'ai-r2', title: 'Scikit-learn Documentation', type: 'link', url: '#' },
    ],
  },
  {
    id: 4,
    category: 'Advanced UI/UX Design',
    title: 'Crafting Digital Experiences',
    instructor: 'Lina Aboud',
    instructorTitle: 'Senior Product Designer',
    instructorBio: 'Lina has designed products used by millions and teaches design thinking at Compass Academy.',
    level: 'Intermediate',
    duration: '7 Weeks',
    lessons: 20,
    rating: 4.7,
    students: 860,
    price: 129,
    coverImage: coverUiux,
    description: 'Master the principles of UI/UX design and learn how to craft delightful, user-centered digital products.',
    whatYouWillLearn: [
      'User research & personas',
      'Wireframing & prototyping',
      'Visual design principles',
      'Usability testing',
    ],
    requirements: ['Figma installed', 'Basic design sense'],
    modules: [
      {
        id: 'ux-m1',
        title: 'Research & Personas',
        lessons: [
          { id: 'ux-l1', title: 'User Interviews', duration: '12 min',
            content: 'Learn how to plan and run user interviews that reveal real needs, not assumptions.',
            keyPoints: ['Writing interview scripts', 'Avoiding leading questions', 'Synthesizing findings'] },
          { id: 'ux-l2', title: 'Building Personas', duration: '15 min',
            content: 'Turn research data into actionable personas that guide design decisions.',
            keyPoints: ['Persona structure', 'Prioritizing user needs', 'Sharing personas with teams'] },
        ],
      },
      {
        id: 'ux-m2',
        title: 'Wireframing & Prototyping',
        lessons: [
          { id: 'ux-l3', title: 'Low-Fidelity Wireframes', duration: '14 min',
            content: 'Sketch quick wireframes to explore layout ideas before investing in visual design.',
            keyPoints: ['Speed over polish', 'Information hierarchy', 'Common wireframe mistakes'] },
          { id: 'ux-l4', title: 'Interactive Prototypes in Figma', duration: '20 min',
            content: 'Build a clickable prototype in Figma to test flows with real users.',
            keyPoints: ['Figma prototyping mode', 'Linking frames', 'Testing with users'] },
        ],
      },
      {
        id: 'ux-m3',
        title: 'Visual Design & Testing',
        lessons: [
          { id: 'ux-l5', title: 'Typography & Color Systems', duration: '16 min',
            content: 'Build a consistent type scale and color system that scales across a whole product.',
            keyPoints: ['Type scale basics', 'Color accessibility', 'Design tokens'] },
          { id: 'ux-l6', title: 'Usability Testing Methods', duration: '18 min',
            content: 'Run a moderated usability test session and turn findings into design fixes.',
            keyPoints: ['Task-based testing', 'Think-aloud protocol', 'Prioritizing fixes'] },
        ],
      },
    ],
    assignments: [
      { id: 'ux-a1', title: 'User Persona Document', dueInDays: 4,
        description: 'Create two personas based on the provided user research data.' },
      { id: 'ux-a2', title: 'Prototype Walkthrough', dueInDays: 10,
        description: 'Submit a Figma prototype link with a short walkthrough video.' },
    ],
    resources: [
      { id: 'ux-r1', title: 'Figma Component Library', type: 'link', url: '#' },
      { id: 'ux-r2', title: 'Design Systems Guide', type: 'pdf', url: '#' },
    ],
  },
  {
    id: 5,
    category: 'Full-Stack Web Development',
    title: 'Zero to Deployment',
    instructor: 'Eng. Karim Nasser',
    instructorTitle: 'Full-Stack Engineering Lead',
    instructorBio: 'Karim has built and deployed full-stack products for startups and enterprises alike.',
    level: 'Beginner',
    duration: '12 Weeks',
    lessons: 40,
    rating: 4.8,
    students: 3050,
    price: 179,
    coverImage: coverBusiness,
    description: 'Go from zero to a fully deployed full-stack web application using modern tools and frameworks.',
    whatYouWillLearn: [
      'Front-end with React',
      'Back-end with Node.js',
      'Databases (SQL & NoSQL)',
      'Deployment & hosting',
    ],
    requirements: ['Basic HTML/CSS/JS'],
    modules: [
      {
        id: 'fs-m1',
        title: 'Front-End with React',
        lessons: [
          { id: 'fs-l1', title: 'Components & Props', duration: '15 min',
            content: 'Learn how to break a UI into reusable components and pass data via props.',
            keyPoints: ['Component composition', 'Props vs state', 'Reusability patterns'] },
          { id: 'fs-l2', title: 'Hooks Deep Dive', duration: '20 min',
            content: 'Go beyond useState and explore useEffect, useMemo, and custom hooks.',
            keyPoints: ['useEffect timing', 'Custom hooks', 'Avoiding unnecessary re-renders'] },
        ],
      },
      {
        id: 'fs-m2',
        title: 'Back-End with Node.js',
        lessons: [
          { id: 'fs-l3', title: 'Express Fundamentals', duration: '18 min',
            content: 'Set up an Express server with routing and middleware from scratch.',
            keyPoints: ['Routing basics', 'Middleware chain', 'Error handling'] },
          { id: 'fs-l4', title: 'Building REST APIs', duration: '22 min',
            content: 'Design and implement a full CRUD REST API following best practices.',
            keyPoints: ['REST conventions', 'CRUD endpoints', 'Status codes'] },
        ],
      },
      {
        id: 'fs-m3',
        title: 'Databases & Deployment',
        lessons: [
          { id: 'fs-l5', title: 'SQL vs NoSQL', duration: '17 min',
            content: 'Compare relational and document databases and when to use each.',
            keyPoints: ['Schema design', 'When to choose NoSQL', 'Query performance basics'] },
          { id: 'fs-l6', title: 'Deploying to Production', duration: '19 min',
            content: 'Deploy your full-stack app to a hosting provider with environment variables configured.',
            keyPoints: ['Environment variables', 'CI/CD basics', 'Domain & SSL setup'] },
        ],
      },
    ],
    assignments: [
      { id: 'fs-a1', title: 'Build a REST API', dueInDays: 6,
        description: 'Build a REST API with full CRUD operations for a resource of your choice.' },
      { id: 'fs-a2', title: 'Deploy Full-Stack App', dueInDays: 14,
        description: 'Deploy your complete app (front-end + back-end + database) and submit the live URL.' },
    ],
    resources: [
      { id: 'fs-r1', title: 'MDN React Guide', type: 'link', url: '#' },
      { id: 'fs-r2', title: 'Node.js Best Practices', type: 'pdf', url: '#' },
    ],
  },
  {
    id: 6,
    category: 'Modern Front-End Web Development',
    title: 'React & Tailwind',
    instructor: 'Eng. Hala Saleh',
    instructorTitle: 'Front-End Engineer',
    instructorBio: 'Hala specializes in building fast, accessible interfaces with modern front-end tooling.',
    level: 'Intermediate',
    duration: '5 Weeks',
    lessons: 15,
    rating: 4.5,
    students: 720,
    price: 89,
    description: 'Build modern, responsive user interfaces using React and Tailwind CSS with real project examples.',
    whatYouWillLearn: [
      'React components & hooks',
      'Tailwind CSS utility classes',
      'Responsive design',
      'Building real projects',
    ],
    requirements: ['Basic JavaScript'],
    modules: [
      {
        id: 'rt-m1',
        title: 'React Fundamentals',
        lessons: [
          { id: 'rt-l1', title: 'JSX & Components', duration: '12 min',
            content: 'Understand JSX syntax and how to structure your first React components.',
            keyPoints: ['JSX rules', 'Functional components', 'Rendering lists'] },
          { id: 'rt-l2', title: 'State & Events', duration: '15 min',
            content: 'Handle user interaction using state and event handlers.',
            keyPoints: ['useState basics', 'Event handling', 'Controlled inputs'] },
        ],
      },
      {
        id: 'rt-m2',
        title: 'Styling with Tailwind',
        lessons: [
          { id: 'rt-l3', title: 'Utility Classes', duration: '13 min',
            content: 'Learn Tailwind\'s utility-first approach and how it speeds up styling.',
            keyPoints: ['Utility-first mindset', 'Spacing & sizing scale', 'Customizing theme'] },
          { id: 'rt-l4', title: 'Responsive Design', duration: '16 min',
            content: 'Use Tailwind breakpoints to build interfaces that adapt to any screen size.',
            keyPoints: ['Breakpoint prefixes', 'Mobile-first approach', 'Testing responsiveness'] },
        ],
      },
      {
        id: 'rt-m3',
        title: 'Real Projects',
        lessons: [
          { id: 'rt-l5', title: 'Building a Dashboard UI', duration: '20 min',
            content: 'Combine components and Tailwind styles to build a real dashboard layout.',
            keyPoints: ['Grid layouts', 'Reusable card components', 'Dark mode basics'] },
          { id: 'rt-l6', title: 'Optimizing Performance', duration: '17 min',
            content: 'Identify unnecessary re-renders and optimize component performance.',
            keyPoints: ['React.memo', 'Lazy loading', 'Bundle size basics'] },
        ],
      },
    ],
    assignments: [
      { id: 'rt-a1', title: 'Build a Landing Page', dueInDays: 3,
        description: 'Build a responsive landing page using React and Tailwind CSS.' },
      { id: 'rt-a2', title: 'Responsive Dashboard', dueInDays: 7,
        description: 'Convert the provided dashboard design into a fully responsive React component.' },
    ],
    resources: [
      { id: 'rt-r1', title: 'Tailwind CSS Docs', type: 'link', url: '#' },
      { id: 'rt-r2', title: 'React Patterns Guide', type: 'pdf', url: '#' },
    ],
  },
  {
    id: 7,
    category: 'Backend with Node.js',
    title: 'REST APIs & Databases',
    instructor: 'Eng. Yousef Amin',
    instructorTitle: 'Backend Engineer',
    instructorBio: 'Yousef has built high-traffic APIs and enjoys teaching backend fundamentals from scratch.',
    level: 'Intermediate',
    duration: '9 Weeks',
    lessons: 26,
    rating: 4.6,
    students: 1100,
    price: 139,
    description: 'Learn how to build secure and scalable REST APIs using Node.js, Express, and databases.',
    whatYouWillLearn: [
      'Node.js & Express fundamentals',
      'REST API design',
      'Authentication & authorization',
      'Database integration',
    ],
    requirements: ['JavaScript basics'],
    modules: [
      {
        id: 'bn-m1',
        title: 'Node & Express Basics',
        lessons: [
          { id: 'bn-l1', title: 'Setting Up Express', duration: '14 min',
            content: 'Get an Express server running and understand the request/response cycle.',
            keyPoints: ['Server setup', 'Request/response cycle', 'Basic routing'] },
          { id: 'bn-l2', title: 'Routing & Middleware', duration: '17 min',
            content: 'Organize routes and build custom middleware for logging and validation.',
            keyPoints: ['Router organization', 'Custom middleware', 'Validation middleware'] },
        ],
      },
      {
        id: 'bn-m2',
        title: 'REST API Design',
        lessons: [
          { id: 'bn-l3', title: 'RESTful Principles', duration: '16 min',
            content: 'Understand the conventions that make an API predictable and easy to consume.',
            keyPoints: ['Resource naming', 'HTTP verbs', 'Statelessness'] },
          { id: 'bn-l4', title: 'Error Handling', duration: '18 min',
            content: 'Build a consistent error handling strategy across your API.',
            keyPoints: ['Centralized error handler', 'Meaningful status codes', 'Error response shape'] },
        ],
      },
      {
        id: 'bn-m3',
        title: 'Auth & Databases',
        lessons: [
          { id: 'bn-l5', title: 'JWT Authentication', duration: '19 min',
            content: 'Implement token-based authentication using JSON Web Tokens.',
            keyPoints: ['Token generation', 'Protecting routes', 'Refresh tokens'] },
          { id: 'bn-l6', title: 'MongoDB Integration', duration: '20 min',
            content: 'Connect your API to MongoDB and perform CRUD operations with Mongoose.',
            keyPoints: ['Mongoose schemas', 'CRUD with Mongoose', 'Indexing basics'] },
        ],
      },
    ],
    assignments: [
      { id: 'bn-a1', title: 'Build Auth System', dueInDays: 5,
        description: 'Implement signup/login endpoints secured with JWT.' },
      { id: 'bn-a2', title: 'Connect MongoDB', dueInDays: 11,
        description: 'Integrate MongoDB into your API and implement full CRUD for one resource.' },
    ],
    resources: [
      { id: 'bn-r1', title: 'Express Documentation', type: 'link', url: '#' },
      { id: 'bn-r2', title: 'JWT Handbook', type: 'pdf', url: '#' },
    ],
  },
  {
    id: 8,
    category: 'Cyber Security',
    title: 'Foundations of Ethical Hacking',
    instructor: 'Eng. Mona Rida',
    instructorTitle: 'Security Engineer',
    instructorBio: 'Mona works in offensive security and teaches ethical hacking fundamentals to future engineers.',
    level: 'Advanced',
    duration: '8 Weeks',
    lessons: 22,
    rating: 4.9,
    students: 640,
    price: 159,
    description: 'Understand core cybersecurity concepts and ethical hacking techniques used to secure real systems.',
    whatYouWillLearn: [
      'Networking fundamentals',
      'Common vulnerabilities & attacks',
      'Penetration testing basics',
      'Security best practices',
    ],
    requirements: ['Basic networking knowledge'],
    modules: [
      {
        id: 'cs-m1',
        title: 'Networking Foundations',
        lessons: [
          { id: 'cs-l1', title: 'TCP/IP Basics', duration: '15 min',
            content: 'Understand how data travels across networks using the TCP/IP model.',
            keyPoints: ['OSI vs TCP/IP model', 'IP addressing', 'Packet structure'] },
          { id: 'cs-l2', title: 'Network Protocols', duration: '18 min',
            content: 'Explore common protocols (HTTP, DNS, FTP) and their security implications.',
            keyPoints: ['Common protocols', 'Protocol vulnerabilities', 'Packet sniffing basics'] },
        ],
      },
      {
        id: 'cs-m2',
        title: 'Vulnerabilities & Attacks',
        lessons: [
          { id: 'cs-l3', title: 'Common Attack Vectors', duration: '17 min',
            content: 'Learn how phishing, malware, and social engineering attacks typically work.',
            keyPoints: ['Phishing techniques', 'Malware types', 'Social engineering'] },
          { id: 'cs-l4', title: 'OWASP Top 10', duration: '20 min',
            content: 'Walk through the most common web application vulnerabilities and how to prevent them.',
            keyPoints: ['Injection attacks', 'Broken authentication', 'Security misconfiguration'] },
        ],
      },
      {
        id: 'cs-m3',
        title: 'Penetration Testing',
        lessons: [
          { id: 'cs-l5', title: 'Reconnaissance Techniques', duration: '16 min',
            content: 'Learn passive and active reconnaissance methods used before a penetration test.',
            keyPoints: ['Passive recon', 'Active scanning', 'Information gathering tools'] },
          { id: 'cs-l6', title: 'Reporting Findings', duration: '14 min',
            content: 'Learn how to document vulnerabilities clearly for technical and non-technical audiences.',
            keyPoints: ['Report structure', 'Severity ratings', 'Remediation recommendations'] },
        ],
      },
    ],
    assignments: [
      { id: 'cs-a1', title: 'Vulnerability Scan Report', dueInDays: 6,
        description: 'Run a vulnerability scan on the provided lab environment and document findings.' },
      { id: 'cs-a2', title: 'Pen Test Simulation', dueInDays: 13,
        description: 'Complete the guided penetration testing lab and submit your report.' },
    ],
    resources: [
      { id: 'cs-r1', title: 'OWASP Top 10 Guide', type: 'link', url: '#' },
      { id: 'cs-r2', title: 'Networking Basics PDF', type: 'pdf', url: '#' },
    ],
  },
];