export const coursesData = [
  {
    id: 1,
    category: 'Software Engineering',
    title: 'Designing and building scalable and maintainable software systems.',
    instructor: 'Eng. Ahmad Khalil',
    level: 'Intermediate',
    duration: '8 Weeks',
    lessons: 24,
    rating: 4.8,
    students: 1240,
    price: 149,
    description: 'This course teaches you how to design robust software architectures used in real production systems. You will learn design patterns, system design principles, and how to build applications that scale.',
    whatYouWillLearn: [
      'Software architecture fundamentals',
      'Design patterns & best practices',
      'Scalability and performance optimization',
      'Clean code and maintainability',
    ],
    requirements: ['Basic programming knowledge', 'Understanding of OOP concepts'],
  },
  {
    id: 2,
    category: 'Flutter Masterclass',
    title: 'Build Production-Ready Apps',
    instructor: 'Eng. Sara Youssef',
    level: 'Beginner',
    duration: '6 Weeks',
    lessons: 18,
    rating: 4.6,
    students: 980,
    price: 99,
    description: 'Learn Flutter from scratch and build cross-platform mobile apps ready for the App Store and Google Play.',
    whatYouWillLearn: [
      'Dart programming basics',
      'Flutter widgets & UI building',
      'State management',
      'Publishing apps to stores',
    ],
    requirements: ['No prior experience needed'],
  },
  {
    id: 3,
    category: 'AI Engineering',
    title: 'AI & Machine Learning Engineering: Practical Approach',
    instructor: 'Dr. Omar Fares',
    level: 'Advanced',
    duration: '10 Weeks',
    lessons: 32,
    rating: 4.9,
    students: 2100,
    price: 199,
    description: 'A hands-on course covering machine learning engineering practices used in real AI products, from data pipelines to model deployment.',
    whatYouWillLearn: [
      'Machine learning fundamentals',
      'Model training & evaluation',
      'Deployment pipelines (MLOps)',
      'Real-world AI case studies',
    ],
    requirements: ['Python programming', 'Basic statistics'],
  },
  {
    id: 4,
    category: 'Advanced UI/UX Design',
    title: 'Crafting Digital Experiences',
    instructor: 'Lina Aboud',
    level: 'Intermediate',
    duration: '7 Weeks',
    lessons: 20,
    rating: 4.7,
    students: 860,
    price: 129,
    description: 'Master the principles of UI/UX design and learn how to craft delightful, user-centered digital products.',
    whatYouWillLearn: [
      'User research & personas',
      'Wireframing & prototyping',
      'Visual design principles',
      'Usability testing',
    ],
    requirements: ['Figma installed', 'Basic design sense'],
  },
  {
    id: 5,
    category: 'Full-Stack Web Development',
    title: 'Zero to Deployment',
    instructor: 'Eng. Karim Nasser',
    level: 'Beginner',
    duration: '12 Weeks',
    lessons: 40,
    rating: 4.8,
    students: 3050,
    price: 179,
    description: 'Go from zero to a fully deployed full-stack web application using modern tools and frameworks.',
    whatYouWillLearn: [
      'Front-end with React',
      'Back-end with Node.js',
      'Databases (SQL & NoSQL)',
      'Deployment & hosting',
    ],
    requirements: ['Basic HTML/CSS/JS'],
  },
  {
    id: 6,
    category: 'Modern Front-End Web Development',
    title: 'React & Tailwind',
    instructor: 'Eng. Hala Saleh',
    level: 'Intermediate',
    duration: '5 Weeks',
    lessons: 15,
    rating: 4.5,
    students: 720,
    price: 89,
    description: 'Build modern, responsive user interfaces using React and Tailwind CSS with real project examples.',
    whatYouWillLearn: [
      'React components & hooks',
      'Tailwind CSS utility classes',
      'Responsive design',
      'Building real projects',
    ],
    requirements: ['Basic JavaScript'],
  },
  {
    id: 7,
    category: 'Backend with Node.js',
    title: 'REST APIs & Databases',
    instructor: 'Eng. Yousef Amin',
    level: 'Intermediate',
    duration: '9 Weeks',
    lessons: 26,
    rating: 4.6,
    students: 1100,
    price: 139,
    description: 'Learn how to build secure and scalable REST APIs using Node.js, Express, and databases.',
    whatYouWillLearn: [
      'Node.js & Express fundamentals',
      'REST API design',
      'Authentication & authorization',
      'Database integration',
    ],
    requirements: ['JavaScript basics'],
  },
  {
    id: 8,
    category: 'Cyber Security',
    title: 'Foundations of Ethical Hacking',
    instructor: 'Eng. Mona Rida',
    level: 'Advanced',
    duration: '8 Weeks',
    lessons: 22,
    rating: 4.9,
    students: 640,
    price: 159,
    description: 'Understand core cybersecurity concepts and ethical hacking techniques used to secure real systems.',
    whatYouWillLearn: [
      'Networking fundamentals',
      'Common vulnerabilities & attacks',
      'Penetration testing basics',
      'Security best practices',
    ],
    requirements: ['Basic networking knowledge'],
  },
];