export const projectsData = [
  {
    id: 1,
    title: 'Compass Academy Platform',
    category: 'Web Development',
    team: ['Maha Alashqar', 'Sara Youssef'],
    course: 'Full-Stack Web Development',
    description: 'A digital learning and mentorship platform for engineering students, featuring course management, real-time messaging, and progress tracking.',
    techStack: ['React', 'Vite', 'Context API', 'CSS'],
    likes: 34,
    featured: true,
    links: { demo: '#', github: '#' },
  },
  {
    id: 2,
    title: 'Smart Campus Navigator',
    category: 'Mobile Development',
    team: ['Ahmad Khalil'],
    course: 'Build Production-Ready Apps',
    description: 'A Flutter app that helps new students navigate university campuses using indoor maps and real-time class schedules.',
    techStack: ['Flutter', 'Dart', 'Firebase'],
    likes: 21,
    featured: false,
    links: { demo: '#', github: '#' },
  },
  {
    id: 3,
    title: 'AI Study Companion',
    category: 'Artificial Intelligence',
    team: ['Omar Fares', 'Lina Aboud'],
    course: 'AI & Machine Learning Engineering',
    description: 'An AI-powered chatbot that summarizes lecture notes and generates practice quizzes tailored to each student.',
    techStack: ['Python', 'scikit-learn', 'Flask'],
    likes: 48,
    featured: true,
    links: { demo: '#', github: '#' },
  },
  {
    id: 4,
    title: 'Campus Marketplace',
    category: 'Web Development',
    team: ['Karim Nasser', 'Hala Saleh'],
    course: 'Zero to Deployment',
    description: 'A peer-to-peer marketplace where students can buy and sell used textbooks and equipment securely within campus.',
    techStack: ['Node.js', 'Express', 'MongoDB', 'React'],
    likes: 27,
    featured: false,
    links: { demo: '#', github: '#' },
  },
  {
    id: 5,
    title: 'Secure Exam Portal',
    category: 'Cyber Security',
    team: ['Mona Rida'],
    course: 'Foundations of Ethical Hacking',
    description: 'A hardened online exam portal built with lockdown-browser style restrictions and detailed penetration test documentation.',
    techStack: ['Node.js', 'JWT', 'OWASP practices'],
    likes: 19,
    featured: false,
    links: { demo: '#', github: '#' },
  },
  {
    id: 6,
    category: 'Data Science',
    title: 'Student Performance Predictor',
    team: ['Yousef Amin', 'Maha Alashqar'],
    course: 'AI & Machine Learning Engineering',
    description: 'A predictive model that flags students at risk of falling behind, using historical grades and engagement data.',
    techStack: ['Python', 'Pandas', 'scikit-learn'],
    likes: 39,
    featured: true,
    links: { demo: '#', github: '#' },
  },
  {
    id: 7,
    title: 'Design System for Compass Academy',
    category: 'UI/UX Design',
    team: ['Lina Aboud'],
    course: 'Crafting Digital Experiences',
    description: 'A full component library and design token system used to unify Compass Academy\'s visual identity across all pages.',
    techStack: ['Figma', 'Design Tokens'],
    likes: 25,
    featured: false,
    links: { demo: '#', github: '#' },
  },
  {
    id: 8,
    title: 'Dorm Maintenance Tracker',
    category: 'Web Development',
    team: ['Hala Saleh'],
    course: 'React & Tailwind',
    description: 'A lightweight tool for students to report and track maintenance issues in university dormitories.',
    techStack: ['React', 'Tailwind CSS'],
    likes: 14,
    featured: false,
    links: { demo: '#', github: '#' },
  },
];

export const PROJECT_CATEGORIES = [
  'Web Development',
  'Mobile Development',
  'Artificial Intelligence',
  'Cyber Security',
  'Data Science',
  'UI/UX Design',
];